// <auto-generated />
using System;
using CarMaintanance.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarMaintanance.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20230109222250_Migration21")]
    partial class Migration21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarMaintanance.Model.Areas", b =>
                {
                    b.Property<int>("AreaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaID"));

                    b.Property<bool>("AreaVehicular")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("AreaID");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("CarMaintanance.Model.Clientes", b =>
                {
                    b.Property<int>("ClienteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteID"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ClienteID");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("CarMaintanance.Model.Facturas", b =>
                {
                    b.Property<int>("FacturasID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturasID"));

                    b.Property<int?>("ClientesClienteID")
                        .HasColumnType("int");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("SolicitudID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("FacturasID");

                    b.HasIndex("ClientesClienteID");

                    b.HasIndex("SolicitudID")
                        .IsUnique();

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("CarMaintanance.Model.Modulos", b =>
                {
                    b.Property<int>("ModuloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuloId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("ModuloId");

                    b.ToTable("Modulos");
                });

            modelBuilder.Entity("CarMaintanance.Model.Perfiles", b =>
                {
                    b.Property<int>("PerfilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilID"));

                    b.Property<int>("AreaID")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("PerfilID");

                    b.HasIndex("AreaID");

                    b.ToTable("Perfiles");
                });

            modelBuilder.Entity("CarMaintanance.Model.PerfilesModulos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("ModuloID")
                        .HasColumnType("int");

                    b.Property<int>("PerfilID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ModuloID");

                    b.HasIndex("PerfilID");

                    b.ToTable("PerfilesModulos");
                });

            modelBuilder.Entity("CarMaintanance.Model.PerfilesRoles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PerfilID")
                        .HasColumnType("int");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PerfilID");

                    b.HasIndex("RolID");

                    b.ToTable("PerfilesRoles");
                });

            modelBuilder.Entity("CarMaintanance.Model.Recordatorios", b =>
                {
                    b.Property<int>("RecordatorioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordatorioID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<bool>("Completado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRecordatorio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("RecordatorioID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Recordatorios");
                });

            modelBuilder.Entity("CarMaintanance.Model.Roles", b =>
                {
                    b.Property<int>("RolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolID"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("RolID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CarMaintanance.Model.Solicitudes", b =>
                {
                    b.Property<int>("SolicitudID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudID"));

                    b.Property<int>("ClienteID")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Despachada")
                        .HasColumnType("bit");

                    b.Property<bool>("Facturada")
                        .HasColumnType("bit");

                    b.Property<int>("FacturasID")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("SolicitudID");

                    b.HasIndex("ClienteID");

                    b.ToTable("Solicitudes");
                });

            modelBuilder.Entity("CarMaintanance.Model.SolicitudesHijas", b =>
                {
                    b.Property<int>("SolicitudHijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SolicitudHijaID"));

                    b.Property<int>("AreaID")
                        .HasColumnType("int");

                    b.Property<bool>("Completada")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Facturada")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<float>("Precio")
                        .HasColumnType("real");

                    b.Property<int>("SolicitudID")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.HasKey("SolicitudHijaID");

                    b.HasIndex("AreaID");

                    b.HasIndex("SolicitudID");

                    b.ToTable("SolicitudesHijas");
                });

            modelBuilder.Entity("CarMaintanance.Model.Usuarios", b =>
                {
                    b.Property<int>("UsuarioID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioID"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<DateTime>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(40)");

                    b.Property<int>("RolID")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioID");

                    b.HasIndex("RolID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CarMaintanance.Model.Facturas", b =>
                {
                    b.HasOne("CarMaintanance.Model.Clientes", null)
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("ClientesClienteID");

                    b.HasOne("CarMaintanance.Model.Solicitudes", "Solicitud")
                        .WithOne("Factura")
                        .HasForeignKey("CarMaintanance.Model.Facturas", "SolicitudID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("CarMaintanance.Model.Perfiles", b =>
                {
                    b.HasOne("CarMaintanance.Model.Areas", "Area")
                        .WithMany("Perfil")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("CarMaintanance.Model.PerfilesModulos", b =>
                {
                    b.HasOne("CarMaintanance.Model.Modulos", "Modulos")
                        .WithMany("PerfilModuloDetalle")
                        .HasForeignKey("ModuloID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarMaintanance.Model.Perfiles", "Perfil")
                        .WithMany("PerfilModuloDetalle")
                        .HasForeignKey("PerfilID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Modulos");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("CarMaintanance.Model.PerfilesRoles", b =>
                {
                    b.HasOne("CarMaintanance.Model.Perfiles", "Perfil")
                        .WithMany("PerfilesRoles")
                        .HasForeignKey("PerfilID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarMaintanance.Model.Roles", "Rol")
                        .WithMany("PefilesRoles")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Perfil");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CarMaintanance.Model.Recordatorios", b =>
                {
                    b.HasOne("CarMaintanance.Model.Clientes", "Cliente")
                        .WithMany("RecordatorioList")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CarMaintanance.Model.Solicitudes", b =>
                {
                    b.HasOne("CarMaintanance.Model.Clientes", "Cliente")
                        .WithMany("DetalleSolicitud")
                        .HasForeignKey("ClienteID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("CarMaintanance.Model.SolicitudesHijas", b =>
                {
                    b.HasOne("CarMaintanance.Model.Areas", "Area")
                        .WithMany("Hijas")
                        .HasForeignKey("AreaID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CarMaintanance.Model.Solicitudes", "Solicitud")
                        .WithMany("Detalle")
                        .HasForeignKey("SolicitudID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Area");

                    b.Navigation("Solicitud");
                });

            modelBuilder.Entity("CarMaintanance.Model.Usuarios", b =>
                {
                    b.HasOne("CarMaintanance.Model.Roles", "Rol")
                        .WithMany("Usuario")
                        .HasForeignKey("RolID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("CarMaintanance.Model.Areas", b =>
                {
                    b.Navigation("Hijas");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("CarMaintanance.Model.Clientes", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("DetalleSolicitud");

                    b.Navigation("RecordatorioList");
                });

            modelBuilder.Entity("CarMaintanance.Model.Modulos", b =>
                {
                    b.Navigation("PerfilModuloDetalle");
                });

            modelBuilder.Entity("CarMaintanance.Model.Perfiles", b =>
                {
                    b.Navigation("PerfilModuloDetalle");

                    b.Navigation("PerfilesRoles");
                });

            modelBuilder.Entity("CarMaintanance.Model.Roles", b =>
                {
                    b.Navigation("PefilesRoles");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("CarMaintanance.Model.Solicitudes", b =>
                {
                    b.Navigation("Detalle");

                    b.Navigation("Factura")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
